**NumPy**

NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.

NumPy also includes a wide range of mathematical functions, such as linear algebra, Fourier transforms, and random number generation, which can be applied to arrays.

**Why Use Numpy**

In Python, we use lists to work with arrays. But when it comes to large array operations, Python lists are not optimized enough.

Numpy arrays are optimized for complex mathematical and statistical operations. Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.

**Import Numpy in python**

In [1]:
import numpy as np

**NumPy Array Creation**

In [2]:
# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]


Instead of creating a list and using the list variable with the np.array() function, we can directly pass list elements as an argument.

In [3]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)


[2 4 6 8]


**Create a 2-D NumPy Array**

In [4]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])


**Create a 3-D NumPy Array**

In [5]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Check Data Type of a NumPy Array**

In [6]:
# create an array of integers
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)


int64


**Check dimensions of an Numpy Array**

In [7]:
print(array1.ndim)

1


**Check Size of Numpy array**

In [8]:
print(array1.size)

3


**NumPy Array shape Attribute**

In NumPy, the shape attribute returns a tuple of integers that gives the size of the array in each dimension

In [9]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)


(2, 3)


**NumPy Array itemsize Attribute**

In NumPy, the itemsize attribute determines size (in bytes) of each element in the array.

In [10]:

# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)
print(array2.itemsize)


8
4


**NumPy Array data Attribute**

In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

In simpler terms, the data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.

In [11]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

# print memory address of array1's and array2's data
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)



Data of array1 is:  <memory at 0x794c46fc9240>
Data of array2 is:  <memory at 0x794c360e7ac0>


**Access Array Elements Using Index**

In [12]:

array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


**Modify Array Elements Using Index**

In [13]:

array1[1]=10
print(array1)

[ 1 10  5  7  9]


**2-D NumPy Array Indexing**

In [25]:

# create a 2D array
array1 = np.array([[11, 13, 15, 17],
                       [29, 21, 43, 55],
                       [2, 4, 66, 78]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 55
2nd Element at First Row: 13


**NumPy Statistical Functions**

Functions

median() return the median of an array

mean() return the mean of an array

std() return the standard deviation of an array

percentile() return the nth percentile of elements in an array

min() return the minimum element of an array

max() return the maximum element of an array

In [15]:

# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)

print(median)

3.0


**Compute Mean Using NumPy**

In [26]:

# create a numpy array
marks = np.array([23, 18, 90, 106, 35])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)

54.4


**Standard Deviation of NumPy Array**

In [27]:
# create a numpy array
marks = np.array([50, 60, 70, 80, 90])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

14.142135623730951


**Numpy Percentile**

In [28]:
# create a numpy array
marks = np.array([19, 18, 17, 16, 15])

# compute the standard deviation of marks
std_marks = np.percentile(marks,50)
print(std_marks)

17.0


**Numpy min**

In [30]:
# create a numpy array
marks = np.array([45, 95, 75, 66, 10])

# compute the standard deviation of marks
std_marks = np.min(marks)
print(std_marks)

10


**Numpy max**

In [31]:

# create a numpy array
marks = np.array([76, 50, 78, 67, 100])

# compute the standard deviation of marks
std_marks = np.max(marks)
print(std_marks)

100


**Array Arithmetic Operations**

In [32]:

# Import `numpy` as `np`
import numpy as np
x = np.array([[5, 16, 20], [23, 41, 50]])
y = np.array([16,67,18])

# Add `x` and `y`
z = np.add(x,y)
print("Addition of x and y:\n", z)

# Subtract `x` and `y`
z = np.subtract(x,y)
print("Subtraction of y from x:\n", z)

# Multiply `x` and `y`
z = np.multiply(x,y)
print("Element-wise multiplication of x and y:\n", z)


Addition of x and y:
 [[ 21  83  38]
 [ 39 108  68]]
Subtraction of y from x:
 [[-11 -51   2]
 [  7 -26  32]]
Element-wise multiplication of x and y:
 [[  80 1072  360]
 [ 368 2747  900]]


**Append Arrays**

In [33]:
import numpy as np

my_array = np.array([1,12,5,10])

# Print `my_array` before appending
print("my_array before appending:", my_array)

# Append a 1D array to `my_array`
new_array = np.append(my_array, [7, 18, 9, 10])

# Print `new_array`
print("new_array:", new_array)

# Print `my_array` after appending
print("my_array after appending:", my_array)

my_array before appending: [ 1 12  5 10]
new_array: [ 1 12  5 10  7 18  9 10]
my_array after appending: [ 1 12  5 10]


**Appending to my_2d_array:**

In [34]:
import numpy as np

my_2d_array = np.array([[11,2,13,4], [52,6,7,81]], dtype=np.int64)

# Print `my_2d_array` before appending
print("my_2d_array before appending:\n", my_2d_array)

# Append an extra column to `my_2d_array`
new_2d_array = np.append(my_2d_array, [[7], [8]], axis=1)

# Print `new_2d_array`
print("new_2d_array:\n", new_2d_array)

# Print `my_2d_array` after appending
print("my_2d_array after appending:\n", my_2d_array)

my_2d_array before appending:
 [[11  2 13  4]
 [52  6  7 81]]
new_2d_array:
 [[11  2 13  4  7]
 [52  6  7 81  8]]
my_2d_array after appending:
 [[11  2 13  4]
 [52  6  7 81]]


**Insert and Delete Array Elements**

In [36]:

import numpy as np
my_array = np.array([12,2,13,4])
my_2d_array = np.array([[1,2,31,4], [5,16,7,82]], dtype=np.int64)

# Insert `5` at index 1
np.insert(my_array, 1, 4)

# Delete the value at index 1
np.delete(my_array,[1])

array([12, 13,  4])